# Generated by Django 4.2.4 on 2023-09-03 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctors", "0009_remove_doctormodel_email_remove_doctormodel_fullname"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientModel",
            fields=[
                ("patient_id", models.AutoField(primary_key=True, serialize=False)),
                ("last_checkup", models.DateTimeField(blank=True, null=True)),
                ("first_checkup", models.DateTimeField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("diseases_history", models.TextField(blank=True, null=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctors",
                    models.ManyToManyField(
                        related_name="patients", to="doctors.doctormodel"
                    ),
                ),
            ],
        ),
    ]
