# Generated by Django 4.2.4 on 2023-09-03 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0009_remove_doctormodel_email_remove_doctormodel_fullname"),
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "disease_syndrome",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_new", models.BooleanField(default=True)),
                ("appointment_time", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment",
                        to="doctors.doctormodel",
                    ),
                ),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment",
                        to="patients.patientmodel",
                    ),
                ),
            ],
        ),
    ]
