# Generated by Django 4.2.4 on 2023-09-03 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0009_remove_doctormodel_email_remove_doctormodel_fullname"),
        ("patients", "0002_appointmentmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentmodel",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment",
                to="doctors.doctormodel",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentmodel",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointment",
                to="patients.patientmodel",
            ),
        ),
    ]
