# Generated by Django 4.2.4 on 2023-09-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0003_alter_appointmentmodel_doctor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointmentmodel",
            name="patient",
        ),
        migrations.AddField(
            model_name="appointmentmodel",
            name="patient_age",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointmentmodel",
            name="patient_contact",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="appointmentmodel",
            name="patient_name",
            field=models.CharField(default="patient", max_length=255),
            preserve_default=False,
        ),
    ]
