# Generated by Django 4.2.4 on 2023-09-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0004_remove_appointmentmodel_patient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentmodel",
            name="patient_contact",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
