# Generated by Django 4.2.4 on 2023-09-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patients", "0005_alter_appointmentmodel_patient_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentmodel",
            name="patient_contact",
            field=models.CharField(default="0", max_length=255),
            preserve_default=False,
        ),
    ]
