# Generated by Django 4.2.4 on 2023-09-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0002_appointmentday_doctormodel_delete_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctormodel",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
