# Generated by Django 4.2.4 on 2023-09-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0004_rename_id_doctormodel_doctor_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctormodel",
            name="appointment_available_days",
        ),
        migrations.DeleteModel(
            name="AppointmentDay",
        ),
        migrations.AddField(
            model_name="doctormodel",
            name="appointment_available_days",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monday", "Monday"),
                    ("tuesday", "Tuesday"),
                    ("wednesday", "Wednesday"),
                    ("thursday", "Thursday"),
                    ("friday", "Friday"),
                    ("saturday", "Saturday"),
                    ("sunday", "Sunday"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
