# Generated by Django 4.2.4 on 2023-09-02 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctors", "0005_remove_doctormodel_appointment_available_days_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctormodel",
            name="user",
        ),
        migrations.AddField(
            model_name="doctormodel",
            name="account",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
