# Generated by Django 4.2.4 on 2023-09-02 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doctors", "0008_doctormodel_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctormodel",
            name="email",
        ),
        migrations.RemoveField(
            model_name="doctormodel",
            name="fullname",
        ),
    ]
